name: Deploy buy runner

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .

  prepare-environment:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Stop and remove containers, networks
        run: docker-compose down -v
      - name: Remove unused data
        run: docker system prune -a -f

  deploy:
    needs: prepare-environment
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: docker-compose
        run: docker-compose up -d
